// <auto-generated />
namespace DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class daniestmenuoptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(daniestmenuoptions));
        
        string IMigrationMetadata.Id
        {
            get { return "201707080047243_dani est menu options"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
