// <auto-generated />
namespace DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Añadiraulayupdateicon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Añadiraulayupdateicon));
        
        string IMigrationMetadata.Id
        {
            get { return "201706282147128_Añadir aula y update icon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
